import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import DataProvider from "@/context/DataProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "App Colmena",
  description: "Generated by create next app",
};


async function getList() {
  const res = await fetch(`https://jsonplaceholder.typicode.com/comments?page=1&limit=5`)
  return res.json();
}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {

  const data = await getList();

  return (
    <html lang="es">
      <DataProvider data={data}>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          {children}
        </body>
      </DataProvider>
    </html>
  );
}

